version: 2
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/pitchblack-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      PBRP_BRANCH: 'mtk'
      VERSION: '2.9.0'
      VENDOR: 'nokia'
      CODENAME: 'heart'
      BUILD_LUNCH: 'omni_heart-userdebug'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            # device/qcom/common from TeamWin:android-6.0 is already there
            # git clone https://github.com/CyanogenMod/android_device_qcom_common device/qcom/common -b cm-13.0
            rm -rf external/f2fs-tools && git clone https://github.com/omnirom/android_external_f2fs-tools external/f2fs-tools -b android-7.1
            source build.sh ${SFUserName} ${SFPassword} ${GITHUB_TOKEN}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
